### ISSUE TITLE
isRequiredIf doesn't work well with array items

### ISSUE THREAD

**Issue by JeffreyATW** [jfairbank/revalidate#14]
The newly added `isRequiredIf` checks **all** values of a form to see if a field should be required. But in my case, I only want to check if a specific field within the same object as another field is populated.

e.g.:
```js
{
  childFields: [
    {
      shouldFooBeRequired: true,
      foo: '',
    },
    {
      shouldFooBeRequired: false,
      foo: '',
    },
  ],
}
```

There's no way with `isRequiredIf` to make `childFields[0].foo` be required, while `childFields[1].foo` stays optional.

I was thinking of submitting a PR to pass `value` as a second parameter into the `condition` function, but that's no good as I don't think it will enable me to figure out where `value` lives within the array.

Any suggestions? Thanks!

**Comment by JeffreyATW** [comment]
I think what I might be recommending here is the optional passing of a **third** parameter to `validate` that passes in the values from the current object, compared to all form values. That might make the `validate` API a little messy, but I can't think of a good backwards-compatible way of solving the problem otherwise.

**Comment by jfairbank** [comment]
Hi, @JeffreyATW!

Your recommendation is easily doable with the current code. I think I'm OK with it, but I want some time to play with the change before I commit to it. In the interim, you should be able to accomplish this with a composed validator:

```js
function customIsRequiredIf(condition) {
  return createValidator(
    message => context => {
      if (context && condition(context)) {
        return message;
      }
    },

    field => `${field} is required`
  );
}

const validate = combineValidators({
  'childFields[]': composeValidators({
    foo: customIsRequiredIf(
      context => context.shouldFooBeRequired
    )('Foo'),
  })({ multiple: true }),
});

const result = validate({
  childFields: [
    { shouldFooBeRequired: true, foo: '' },
    { shouldFooBeRequired: false, foo: '' },
  ],
});

console.log(result);
// { childFields: [ { foo: 'Foo is required' }, {} ] }
```

**Comment by JeffreyATW** [comment]
Ah, right, you can provide multiple errors as an object.

It turns out my state was actually a little different, in that the required flag was requiring that children of an array are all required or not:

```js
{
  childFields: [
    {
      shouldGrandchildFieldsBeRequired: true,
      grandchildFields: [
        '',
        '',
        '',
      ],
    },
    {
      shouldGrandchildFieldsBeRequired: false,
      grandchildFields: [
        '',
        '',
        '',
      ],
    },
  ],
}
```

But I was able to take the `multiple: true` setting and get this to work:

```js
combineValidators({
  'childFields[]': composeValidators({
    grandchildFields: createValidator(
      message => context => {
        if (context && context.shouldGrandchildFieldsBeRequired) {
          const messages = [];
          context.grandchildFields.forEach(() => {
            messages.push(message);
          });
          return messages;
        }
        return undefined;
      },

      field => `${field} is required`
    )('Grandchild Field'),
  })({ multiple: true }),
});
```

Thanks!
