### ISSUE TITLE
Nested fields

### ISSUE THREAD

**Issue by fitz0019** [jfairbank/revalidate#3]
The structure of my form is split into two objects and the keys are 'contact.title', 'contact.firstName' etc... From what I can tell CombineReducers is expecting a flat structure. Is this something you could add support for?

Thanks!

**Comment by jfairbank** [comment]
Hi, @fitz0019!

You should be able to call `combineValidators` multiple times to deal with nested objects:

```js
import { combineValidators, isRequired } from 'revalidate';

const validate = combineValidators({
  contact: combineValidators({
    title: isRequired('Title'),
    firstName: isRequired('First Name')
  }),

  car: combineValidators({
    make: isRequired('Make'),
    model: isRequired('Model')
  })
});

const values = { contact: {}, car: {} };

console.log(validate(values));

// {
//   contact: {
//     title: 'Title is required',
//     firstName: 'First Name is required'
//   },
// 
//   car: {
//     make: 'Make is required',
//     model: 'Model is required'
//   }
// }
```

Will this work for you, or is there something specific about your use case I'm not seeing?

**Comment by fabarea** [comment]
The nested object validation has worked out for me way as you described. But what about validation of array values having 0 to n children? Taking the example above, let assume the "contact" could have 0 to many **cars**. Whenever a car is given, the make + model is then required. Kind of dynamic validation... What would be the approach? In the context of Redux Form they use a [validateDeepForm](http://redux-form.com/5.2.3/#/examples/deep) which I can't adapt using revalidate. Thanks for your insight.

**Comment by fabarea** [comment]
Looks good. I tested the example above and it has worked fine. One more question regarding 0 - n array values. Let assume the contact can have 0 - n **cars**. If a car is present, the make + model are then required. What would be the validator?

e.g.

```
const values = { contact: {}, cars: [] };
const values = { contact: {}, cars: [{make: 'foo', model: 'foo'}] };
const values = { contact: {}, cars: [{make: 'foo', model: 'foo'}, {make: 'bar', model: 'bar'}] };
```

**Comment by jfairbank** [comment]
@fabarea That is definitely a compelling use case that I had thought of too. Using multiple calls to `combineValidators` works fine for nested objects, but it is potentially worth supporting some nested field abstraction for arrays. Ideally, it would then support nested objects too, making the above workaround unnecessary. I'm leaning toward the nested field syntax from redux-form, but I do want to at least play around with other API ideas before committing to one particular abstraction. For now, you could try wrapping the validators with a function.

```js
const contactValidator = combineValidators({
  title: isRequired('Title'),
  firstName: isRequired('First Name'),
});

const carValidator = combineValidators({
  make: isRequired('Make'),
  model: isRequired('Model'),
});

function validate(values) {
  return {
    contact: contactValidator(values.contact),
    cars: values.cars.map(carValidator),
  };
}

const values = { contact: {}, cars: [{}] };

console.log(JSON.stringify(validate(values), null, 2));

// {
//   contact: {
//     title: 'Title is required',
//     firstName: 'First Name is required',
//   },
//
//   cars: [
//     {
//       make: 'Make is required',
//       model: 'Model is required',
//     },
//   ],
// }
```

**Comment by fabarea** [comment]
Thanks for the hint. Yeah, it works like that - I ended up with a similar solution while digging :) Good to know you have / want a long term solution for complex nested objects.

**Comment by jfairbank** [comment]
@fitz0019 @fabarea I've added support for nested fields via the same syntax that redux form uses. The latest release v0.2.1 should have nested field support. Let me know if you encounter any bugs/issues. Closing this issue. Thanks!

**Comment by fabarea** [comment]
Just a feedback... [works](https://github.com/jfairbank/revalidate#nested-fields) great! :)
